name: Run Python Test
on:
  push:
jobs:
  build:
    name: run python
    runs-on: ubundu-lastest
    steps: 
    - uses: actions/checkout@v2
    - name: Run python
      run: |
        python3 test.py